// Code generated by the Lingua Franca compiler from file:
// /Users/ra/git/lingua-franca/example/Denso/SpatAnalysis/MQTTSubscriber.lf
#include "ctarget.h"
#define NUMBER_OF_FEDERATES 1
#include "core/reactor.c"
