name: Install Patmos and dependencies (Linux only)
description: Install Patmos and dependencies (Linux only)
runs:
  using: "composite"
  steps:
    - name: Install required packages
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y git openjdk-11-jdk cmake make g++ texinfo flex bison \
          subversion libelf-dev graphviz libboost-dev libboost-program-options-dev ruby-full \
          liblpsolve55-dev zlib1g-dev gtkwave gtkterm scala autoconf libfl2 expect verilator curl chrpath

    - name: Setup sbt
      uses: sbt/setup-sbt@v1

    - name: Clone and build Patmos
      shell: bash
      run: |
        export PATH=$PATH:$HOME/t-crest/local/bin
        echo "PATH=$PATH:$HOME/t-crest/local/bin" >> "$GITHUB_ENV"
        echo $PATH
        mkdir ~/t-crest
        cd ~/t-crest
        git clone https://github.com/t-crest/patmos-misc.git misc
        ./misc/build.sh -qm toolchain1
        patmos-clang --version
        which patmos-clang
