/**
 * generated by Xtext 2.17.0
 */
package org.icyphy.linguaFranca;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Composite</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.icyphy.linguaFranca.Composite#getInstances <em>Instances</em>}</li>
 *   <li>{@link org.icyphy.linguaFranca.Composite#getConnections <em>Connections</em>}</li>
 * </ul>
 *
 * @see org.icyphy.linguaFranca.LinguaFrancaPackage#getComposite()
 * @model
 * @generated
 */
public interface Composite extends Component
{
  /**
   * Returns the value of the '<em><b>Instances</b></em>' containment reference list.
   * The list contents are of type {@link org.icyphy.linguaFranca.Instance}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Instances</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instances</em>' containment reference list.
   * @see org.icyphy.linguaFranca.LinguaFrancaPackage#getComposite_Instances()
   * @model containment="true"
   * @generated
   */
  EList<Instance> getInstances();

  /**
   * Returns the value of the '<em><b>Connections</b></em>' containment reference list.
   * The list contents are of type {@link org.icyphy.linguaFranca.Connection}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Connections</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connections</em>' containment reference list.
   * @see org.icyphy.linguaFranca.LinguaFrancaPackage#getComposite_Connections()
   * @model containment="true"
   * @generated
   */
  EList<Connection> getConnections();

} // Composite
