/**
 * generated by Xtext 2.16.0
 */
package org.icyphy.linguaFranca;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Trigger</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.icyphy.linguaFranca.Trigger#getName <em>Name</em>}</li>
 *   <li>{@link org.icyphy.linguaFranca.Trigger#getPeriod <em>Period</em>}</li>
 * </ul>
 *
 * @see org.icyphy.linguaFranca.LinguaFrancaPackage#getTrigger()
 * @model
 * @generated
 */
public interface Trigger extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.icyphy.linguaFranca.LinguaFrancaPackage#getTrigger_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.icyphy.linguaFranca.Trigger#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Period</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Period</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Period</em>' containment reference.
   * @see #setPeriod(Period)
   * @see org.icyphy.linguaFranca.LinguaFrancaPackage#getTrigger_Period()
   * @model containment="true"
   * @generated
   */
  Period getPeriod();

  /**
   * Sets the value of the '{@link org.icyphy.linguaFranca.Trigger#getPeriod <em>Period</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Period</em>' containment reference.
   * @see #getPeriod()
   * @generated
   */
  void setPeriod(Period value);

} // Trigger
