#ifndef REACTOR_CPP_CONFIG_HH
#define REACTOR_CPP_CONFIG_HH

// NOLINTNEXTLINE
/* #undef REACTOR_CPP_PRINT_STATISTICS */
// NOLINTNEXTLINE
/* #undef REACTOR_CPP_TRACE */
// NOLINTNEXTLINE
#define REACTOR_CPP_VALIDATE
// NOLINTNEXTLINE
#define REACTOR_CPP_LOG_LEVEL 3

#endif
