/*
 * generated by Xtext 2.17.0
 */
package org.icyphy.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.icyphy.linguafranca.ui.internal.LinguafrancaActivator;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LinguaFrancaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(LinguafrancaActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		LinguafrancaActivator activator = LinguafrancaActivator.getInstance();
		return activator != null ? activator.getInjector(LinguafrancaActivator.ORG_ICYPHY_LINGUAFRANCA) : null;
	}

}
