/*
 * generated by Xtext 2.26.0
 */
package org.lflang.formatting2;

import java.util.List;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.FormatterRequest;
import org.eclipse.xtext.formatting2.IFormatter2;
import org.eclipse.xtext.formatting2.regionaccess.ITextReplacement;
import org.eclipse.xtext.formatting2.regionaccess.ITextSegment;
import org.eclipse.xtext.formatting2.regionaccess.internal.TextReplacement;

import org.lflang.ast.ToLf;

public class LFFormatter implements IFormatter2 {

	@Override
	public List<ITextReplacement> format(FormatterRequest request) {
		ITextSegment documentRegion = request.getTextRegionAccess().regionForDocument();
		List<EObject> documentContents = request.getTextRegionAccess().getResource().getContents();
		if (documentContents.isEmpty()) return List.of();
		return List.of(
			new TextReplacement(
				request.getTextRegionAccess(),
				documentRegion.getOffset(),
				documentRegion.getLength(),
				ToLf.instance.doSwitch(documentContents.get(0)).toString()
			)
		);
	}
}
