/*
 * generated by Xtext 2.23.0
 */
package org.lflang.tests;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.resource.Resource.Diagnostic;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.lflang.lf.Model;

@ExtendWith(InjectionExtension.class)
@InjectWith(LFInjectorProvider.class)
public class LFParsingTest {
	@Inject
	private ParseHelper<Model> parseHelper;
	
	@Test
	public void loadModel() throws Exception {
		Model result = parseHelper.parse("Hello Xtext!");
		Assertions.assertNotNull(result);
		List<Diagnostic> errors = result.eResource().getErrors();
		Assertions.assertTrue(errors.isEmpty(), "Unexpected errors: " + IterableExtensions.join(errors, ", "));
	}
}
