/*
 * generated by Xtext 2.17.0
 */
package org.icyphy


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class LinguaFrancaStandaloneSetup extends LinguaFrancaStandaloneSetupGenerated {

	def static void doSetup() {
		new LinguaFrancaStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
