/*
 * generated by Xtext 2.25.0
 */

package org.lflang;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 *
 * <p>See {@link LFRuntimeModule}, the base Guice module for LF services.
 */
public class LFStandaloneSetup extends LFStandaloneSetupGenerated {

  protected static Injector injector;

  public static Injector doSetup() {
    if (injector == null) {
      injector = new LFStandaloneSetup().createInjectorAndDoEMFRegistration();
    }
    return injector;
  }

  @Override
  public Injector createInjector() {
    return Guice.createInjector(new LFRuntimeModule());
  }
}
