/*
 * generated by Xtext 2.25.0
 */
package org.lflang.scoping;

/**
 * This class contains custom scoping description.
 *
 * <p>See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping on how and
 * when to use it.
 */
public class LFScopeProvider extends LFScopeProviderImpl {}
