name: lf-c
prepare: ["mkdir", "src"]
copy: ["cp", "-r", "${benchmark.targets.lf-c.copy_sources}", "src"]
gen: ["cog", "-r", "${args:benchmark.targets.lf-c.gen_args}",
      "-D", "workers=${threads}",
      "-D", "scheduler=${target.params.scheduler}",
      "-D", "numIterations=${iterations}",
      "-D", "threading=True",
      "src/${benchmark.targets.lf-c.lf_file}"]
compile: ["${lf_path}/bin/lfc", "src/${benchmark.targets.lf-c.lf_file}"]
run: ["bin/${benchmark.targets.lf-c.binary}"]
parser:
  _target_: "parser.parse_lfc_output"
params:
  scheduler: "GEDF_NP"
