name: lf-rust
prepare: ["mkdir", "src"]
copy: ["cp", "-r", "${benchmark.targets.lf-rust.copy_sources}", "src"]
gen: null
compile: ["${lf_path}/bin/lfc", "src/${benchmark.targets.lf-rust.lf_file}"]
run: [
    "bin/${benchmark.targets.lf-rust.binary}",
      "--main-num-iterations", "${iterations}",
      "--threads", "${threads}",
      "${args:benchmark.targets.lf-rust.run_args}"
]
parser:
  _target_: "parser.parse_lf_rust_output"
