#!/bin/bash
#
# Script to compile the code generated by lfc or by the Lingua Franca IDE
# for the programs in this directory using arguments that are suitable to the 
# OS on which this is running.  The OS is detected using the Posix command uname.
# This script will only work for Posix-compliant platforms such as MacOS and Linux.
# This script is expected to be run in the directory in which the generated code
# and all supporting files are placed.
#
# Usage:
#
#     compile.sh root_file_name
#
# where the root_file_name is one of Rhythm, RhythmDistributed_player1, etc., and
# bin_dir is the directory into which to put the resulting binary.

CC="gcc"

# Identify the operating system
OS=`uname`
if [[ "$OS" == *"Darwin"* ]]
then
    echo "*** Compiling for MacOS"
    echo "*** Current directory is $LF_CURRENT_WORKING_DIRECTORY"
    $CC ${LF_SOURCE_GEN_DIRECTORY}/$1.c \
        ${LF_SOURCE_GEN_DIRECTORY}/core/platform/lf_macos_support.c \
        -o ${LF_BIN_DIRECTORY}/$1 \
        -pthread -DNUMBER_OF_WORKERS=2 \
        -lncurses -framework AudioToolbox -framework CoreFoundation -lm
    echo "*** Bin directory is $LF_BIN_DIRECTORY"

elif [[ "$OS" == *"Linux"* ]]
then
    echo "*** Compiling for Linux"
    echo "*** Current directory is $LF_CURRENT_WORKING_DIRECTORY"
    $CC ${LF_SOURCE_GEN_DIRECTORY}/$1.c \
        ${LF_SOURCE_GEN_DIRECTORY}/core/platform/lf_linux_support.c \
        -o ${LF_BIN_DIRECTORY}/$1 \
        -lpthread -DNUMBER_OF_WORKERS=2 \
        -lncurses -lasound -lm
    echo "*** Bin directory is $LF_BIN_DIRECTORY"
else
    echo "*** Unsupported operating system: ${OS}. Attempting Linux compile."
    echo "*** Current directory is $LF_CURRENT_WORKING_DIRECTORY"
    $CC ${LF_SOURCE_GEN_DIRECTORY}/$1.c \
        ${LF_SOURCE_GEN_DIRECTORY}/core/platform/lf_macos_support.c \
        -o ${LF_BIN_DIRECTORY}/$1 \
        -lpthread -DNUMBER_OF_WORKERS=2 \
        -lncurses -lasound -lm
    echo "*** Bin directory is $LF_BIN_DIRECTORY"
fi

