name: Install ROS2 jazzy (Linux only)
description: Install ROS2 jazzy (Linux only)
runs:
  using: "composite"
  steps:
   - name: Setup ROS2
     uses: ros-tooling/setup-ros@0.7.9
     with:
       required-ros-distributions: jazzy
