/*
 * generated by Xtext 2.17.0
 */
package org.lflang.ide

import org.eclipse.xtext.ide.server.rename.IRenameService2

/**
 * Use this class to register ide components.
 */
class LFIdeModule extends AbstractLFIdeModule {
	override Class<? extends IRenameService2> bindIRenameService2() {
		return TestRenameService
	}
}
