/*
 * generated by Xtext 2.17.0
 */
package org.lflang.ide

import org.eclipse.xtext.ide.server.rename.IRenameService2
import org.eclipse.xtext.ide.server.hover.IHoverService

/**
 * Use this class to register ide components.
 */
class LFIdeModule extends AbstractLFIdeModule {
	
	def Class<? extends IHoverService> bindIHoverService() {
		return HoverService
	}
	
}
