name: Prepare build environment (Linux only)
description: Set up Java, Maven, Gradle, etc.
runs:
  using: "composite"
  steps:
    - name: Set Unix path separator
      run: |
        echo "path-sep=/" >> $GITHUB_ENV
      shell: bash
      if: ${{ runner.os != 'Windows' }}
    - name: Set Windows path separator
      run: |
        echo "path-sep=\\" >> $GITHUB_ENV
      shell: bash
      if: ${{ runner.os == 'Windows' }}
    - name: Set up Java 17
      run: |
        echo "$JAVA_HOME_17_X64/bin" >> $GITHUB_PATH
        echo "org.gradle.java.home=${JAVA_HOME_17_X64//\\/\/}" >> gradle.properties
        echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
      shell: bash
    - name: Check settings
      run: |
        echo $(which java)
        cat gradle.properties
        echo $JAVA_HOME
      shell: bash
    - name: Create hash of Gradle configuration
      run: |
        echo "gradle-hash"="$(find . -type f \( -name "gradle.properties" -o -name "gradle-wrapper.properties" \) -exec cat {} + | sha256sum | cut -d ' ' -f 1)" >> $GITHUB_ENV
      shell: bash
    - name: Remove lock files (Windows)
      run: |
        find . -name ".lock" | xargs rm
      shell: bash
      if: ${{ runner.os == 'Windows' }}
    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~${{ env.path-sep }}.gradle${{ env.path-sep }}caches
          ~${{ env.path-sep }}.gradle${{ env.path-sep }}wrapper
        key: gradle-${{ runner.os }}-${{ env.gradle-hash }}
        # restore-keys: |
        #   ${{ runner.os }}-gradle-
