/*
 * generated by Xtext 2.23.0
 */
package org.lflang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LFUiModule extends AbstractLFUiModule {

	public LFUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
