/**
 * generated by Xtext 2.17.0
 */
package org.icyphy.linguaFranca.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.icyphy.linguaFranca.Composite;
import org.icyphy.linguaFranca.Connection;
import org.icyphy.linguaFranca.Initialize;
import org.icyphy.linguaFranca.Input;
import org.icyphy.linguaFranca.Instance;
import org.icyphy.linguaFranca.LinguaFrancaPackage;
import org.icyphy.linguaFranca.Output;
import org.icyphy.linguaFranca.Params;
import org.icyphy.linguaFranca.Preamble;
import org.icyphy.linguaFranca.Reaction;
import org.icyphy.linguaFranca.Trigger;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Composite</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.icyphy.linguaFranca.impl.CompositeImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.icyphy.linguaFranca.impl.CompositeImpl#getParameters <em>Parameters</em>}</li>
 *   <li>{@link org.icyphy.linguaFranca.impl.CompositeImpl#getInputs <em>Inputs</em>}</li>
 *   <li>{@link org.icyphy.linguaFranca.impl.CompositeImpl#getOutputs <em>Outputs</em>}</li>
 *   <li>{@link org.icyphy.linguaFranca.impl.CompositeImpl#getTriggers <em>Triggers</em>}</li>
 *   <li>{@link org.icyphy.linguaFranca.impl.CompositeImpl#getPreamble <em>Preamble</em>}</li>
 *   <li>{@link org.icyphy.linguaFranca.impl.CompositeImpl#getInitialize <em>Initialize</em>}</li>
 *   <li>{@link org.icyphy.linguaFranca.impl.CompositeImpl#getReactions <em>Reactions</em>}</li>
 *   <li>{@link org.icyphy.linguaFranca.impl.CompositeImpl#getInstances <em>Instances</em>}</li>
 *   <li>{@link org.icyphy.linguaFranca.impl.CompositeImpl#getConnections <em>Connections</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CompositeImpl extends MinimalEObjectImpl.Container implements Composite
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getParameters() <em>Parameters</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParameters()
   * @generated
   * @ordered
   */
  protected Params parameters;

  /**
   * The cached value of the '{@link #getInputs() <em>Inputs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInputs()
   * @generated
   * @ordered
   */
  protected EList<Input> inputs;

  /**
   * The cached value of the '{@link #getOutputs() <em>Outputs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOutputs()
   * @generated
   * @ordered
   */
  protected EList<Output> outputs;

  /**
   * The cached value of the '{@link #getTriggers() <em>Triggers</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTriggers()
   * @generated
   * @ordered
   */
  protected EList<Trigger> triggers;

  /**
   * The cached value of the '{@link #getPreamble() <em>Preamble</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPreamble()
   * @generated
   * @ordered
   */
  protected Preamble preamble;

  /**
   * The cached value of the '{@link #getInitialize() <em>Initialize</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInitialize()
   * @generated
   * @ordered
   */
  protected Initialize initialize;

  /**
   * The cached value of the '{@link #getReactions() <em>Reactions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReactions()
   * @generated
   * @ordered
   */
  protected EList<Reaction> reactions;

  /**
   * The cached value of the '{@link #getInstances() <em>Instances</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInstances()
   * @generated
   * @ordered
   */
  protected EList<Instance> instances;

  /**
   * The cached value of the '{@link #getConnections() <em>Connections</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConnections()
   * @generated
   * @ordered
   */
  protected EList<Connection> connections;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CompositeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LinguaFrancaPackage.Literals.COMPOSITE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LinguaFrancaPackage.COMPOSITE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Params getParameters()
  {
    return parameters;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetParameters(Params newParameters, NotificationChain msgs)
  {
    Params oldParameters = parameters;
    parameters = newParameters;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LinguaFrancaPackage.COMPOSITE__PARAMETERS, oldParameters, newParameters);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setParameters(Params newParameters)
  {
    if (newParameters != parameters)
    {
      NotificationChain msgs = null;
      if (parameters != null)
        msgs = ((InternalEObject)parameters).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LinguaFrancaPackage.COMPOSITE__PARAMETERS, null, msgs);
      if (newParameters != null)
        msgs = ((InternalEObject)newParameters).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LinguaFrancaPackage.COMPOSITE__PARAMETERS, null, msgs);
      msgs = basicSetParameters(newParameters, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LinguaFrancaPackage.COMPOSITE__PARAMETERS, newParameters, newParameters));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Input> getInputs()
  {
    if (inputs == null)
    {
      inputs = new EObjectContainmentEList<Input>(Input.class, this, LinguaFrancaPackage.COMPOSITE__INPUTS);
    }
    return inputs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Output> getOutputs()
  {
    if (outputs == null)
    {
      outputs = new EObjectContainmentEList<Output>(Output.class, this, LinguaFrancaPackage.COMPOSITE__OUTPUTS);
    }
    return outputs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Trigger> getTriggers()
  {
    if (triggers == null)
    {
      triggers = new EObjectContainmentEList<Trigger>(Trigger.class, this, LinguaFrancaPackage.COMPOSITE__TRIGGERS);
    }
    return triggers;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Preamble getPreamble()
  {
    return preamble;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPreamble(Preamble newPreamble, NotificationChain msgs)
  {
    Preamble oldPreamble = preamble;
    preamble = newPreamble;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LinguaFrancaPackage.COMPOSITE__PREAMBLE, oldPreamble, newPreamble);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPreamble(Preamble newPreamble)
  {
    if (newPreamble != preamble)
    {
      NotificationChain msgs = null;
      if (preamble != null)
        msgs = ((InternalEObject)preamble).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LinguaFrancaPackage.COMPOSITE__PREAMBLE, null, msgs);
      if (newPreamble != null)
        msgs = ((InternalEObject)newPreamble).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LinguaFrancaPackage.COMPOSITE__PREAMBLE, null, msgs);
      msgs = basicSetPreamble(newPreamble, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LinguaFrancaPackage.COMPOSITE__PREAMBLE, newPreamble, newPreamble));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Initialize getInitialize()
  {
    return initialize;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInitialize(Initialize newInitialize, NotificationChain msgs)
  {
    Initialize oldInitialize = initialize;
    initialize = newInitialize;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LinguaFrancaPackage.COMPOSITE__INITIALIZE, oldInitialize, newInitialize);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInitialize(Initialize newInitialize)
  {
    if (newInitialize != initialize)
    {
      NotificationChain msgs = null;
      if (initialize != null)
        msgs = ((InternalEObject)initialize).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LinguaFrancaPackage.COMPOSITE__INITIALIZE, null, msgs);
      if (newInitialize != null)
        msgs = ((InternalEObject)newInitialize).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LinguaFrancaPackage.COMPOSITE__INITIALIZE, null, msgs);
      msgs = basicSetInitialize(newInitialize, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LinguaFrancaPackage.COMPOSITE__INITIALIZE, newInitialize, newInitialize));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Reaction> getReactions()
  {
    if (reactions == null)
    {
      reactions = new EObjectContainmentEList<Reaction>(Reaction.class, this, LinguaFrancaPackage.COMPOSITE__REACTIONS);
    }
    return reactions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Instance> getInstances()
  {
    if (instances == null)
    {
      instances = new EObjectContainmentEList<Instance>(Instance.class, this, LinguaFrancaPackage.COMPOSITE__INSTANCES);
    }
    return instances;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Connection> getConnections()
  {
    if (connections == null)
    {
      connections = new EObjectContainmentEList<Connection>(Connection.class, this, LinguaFrancaPackage.COMPOSITE__CONNECTIONS);
    }
    return connections;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LinguaFrancaPackage.COMPOSITE__PARAMETERS:
        return basicSetParameters(null, msgs);
      case LinguaFrancaPackage.COMPOSITE__INPUTS:
        return ((InternalEList<?>)getInputs()).basicRemove(otherEnd, msgs);
      case LinguaFrancaPackage.COMPOSITE__OUTPUTS:
        return ((InternalEList<?>)getOutputs()).basicRemove(otherEnd, msgs);
      case LinguaFrancaPackage.COMPOSITE__TRIGGERS:
        return ((InternalEList<?>)getTriggers()).basicRemove(otherEnd, msgs);
      case LinguaFrancaPackage.COMPOSITE__PREAMBLE:
        return basicSetPreamble(null, msgs);
      case LinguaFrancaPackage.COMPOSITE__INITIALIZE:
        return basicSetInitialize(null, msgs);
      case LinguaFrancaPackage.COMPOSITE__REACTIONS:
        return ((InternalEList<?>)getReactions()).basicRemove(otherEnd, msgs);
      case LinguaFrancaPackage.COMPOSITE__INSTANCES:
        return ((InternalEList<?>)getInstances()).basicRemove(otherEnd, msgs);
      case LinguaFrancaPackage.COMPOSITE__CONNECTIONS:
        return ((InternalEList<?>)getConnections()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LinguaFrancaPackage.COMPOSITE__NAME:
        return getName();
      case LinguaFrancaPackage.COMPOSITE__PARAMETERS:
        return getParameters();
      case LinguaFrancaPackage.COMPOSITE__INPUTS:
        return getInputs();
      case LinguaFrancaPackage.COMPOSITE__OUTPUTS:
        return getOutputs();
      case LinguaFrancaPackage.COMPOSITE__TRIGGERS:
        return getTriggers();
      case LinguaFrancaPackage.COMPOSITE__PREAMBLE:
        return getPreamble();
      case LinguaFrancaPackage.COMPOSITE__INITIALIZE:
        return getInitialize();
      case LinguaFrancaPackage.COMPOSITE__REACTIONS:
        return getReactions();
      case LinguaFrancaPackage.COMPOSITE__INSTANCES:
        return getInstances();
      case LinguaFrancaPackage.COMPOSITE__CONNECTIONS:
        return getConnections();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LinguaFrancaPackage.COMPOSITE__NAME:
        setName((String)newValue);
        return;
      case LinguaFrancaPackage.COMPOSITE__PARAMETERS:
        setParameters((Params)newValue);
        return;
      case LinguaFrancaPackage.COMPOSITE__INPUTS:
        getInputs().clear();
        getInputs().addAll((Collection<? extends Input>)newValue);
        return;
      case LinguaFrancaPackage.COMPOSITE__OUTPUTS:
        getOutputs().clear();
        getOutputs().addAll((Collection<? extends Output>)newValue);
        return;
      case LinguaFrancaPackage.COMPOSITE__TRIGGERS:
        getTriggers().clear();
        getTriggers().addAll((Collection<? extends Trigger>)newValue);
        return;
      case LinguaFrancaPackage.COMPOSITE__PREAMBLE:
        setPreamble((Preamble)newValue);
        return;
      case LinguaFrancaPackage.COMPOSITE__INITIALIZE:
        setInitialize((Initialize)newValue);
        return;
      case LinguaFrancaPackage.COMPOSITE__REACTIONS:
        getReactions().clear();
        getReactions().addAll((Collection<? extends Reaction>)newValue);
        return;
      case LinguaFrancaPackage.COMPOSITE__INSTANCES:
        getInstances().clear();
        getInstances().addAll((Collection<? extends Instance>)newValue);
        return;
      case LinguaFrancaPackage.COMPOSITE__CONNECTIONS:
        getConnections().clear();
        getConnections().addAll((Collection<? extends Connection>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LinguaFrancaPackage.COMPOSITE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case LinguaFrancaPackage.COMPOSITE__PARAMETERS:
        setParameters((Params)null);
        return;
      case LinguaFrancaPackage.COMPOSITE__INPUTS:
        getInputs().clear();
        return;
      case LinguaFrancaPackage.COMPOSITE__OUTPUTS:
        getOutputs().clear();
        return;
      case LinguaFrancaPackage.COMPOSITE__TRIGGERS:
        getTriggers().clear();
        return;
      case LinguaFrancaPackage.COMPOSITE__PREAMBLE:
        setPreamble((Preamble)null);
        return;
      case LinguaFrancaPackage.COMPOSITE__INITIALIZE:
        setInitialize((Initialize)null);
        return;
      case LinguaFrancaPackage.COMPOSITE__REACTIONS:
        getReactions().clear();
        return;
      case LinguaFrancaPackage.COMPOSITE__INSTANCES:
        getInstances().clear();
        return;
      case LinguaFrancaPackage.COMPOSITE__CONNECTIONS:
        getConnections().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LinguaFrancaPackage.COMPOSITE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case LinguaFrancaPackage.COMPOSITE__PARAMETERS:
        return parameters != null;
      case LinguaFrancaPackage.COMPOSITE__INPUTS:
        return inputs != null && !inputs.isEmpty();
      case LinguaFrancaPackage.COMPOSITE__OUTPUTS:
        return outputs != null && !outputs.isEmpty();
      case LinguaFrancaPackage.COMPOSITE__TRIGGERS:
        return triggers != null && !triggers.isEmpty();
      case LinguaFrancaPackage.COMPOSITE__PREAMBLE:
        return preamble != null;
      case LinguaFrancaPackage.COMPOSITE__INITIALIZE:
        return initialize != null;
      case LinguaFrancaPackage.COMPOSITE__REACTIONS:
        return reactions != null && !reactions.isEmpty();
      case LinguaFrancaPackage.COMPOSITE__INSTANCES:
        return instances != null && !instances.isEmpty();
      case LinguaFrancaPackage.COMPOSITE__CONNECTIONS:
        return connections != null && !connections.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //CompositeImpl
