/**
 * generated by Xtext 2.16.0
 */
package org.icyphy.linguaFranca.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import org.icyphy.linguaFranca.Gets;
import org.icyphy.linguaFranca.LinguaFrancaPackage;
import org.icyphy.linguaFranca.Reaction;
import org.icyphy.linguaFranca.Sets;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Reaction</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.icyphy.linguaFranca.impl.ReactionImpl#getTriggers <em>Triggers</em>}</li>
 *   <li>{@link org.icyphy.linguaFranca.impl.ReactionImpl#getGets <em>Gets</em>}</li>
 *   <li>{@link org.icyphy.linguaFranca.impl.ReactionImpl#getSets <em>Sets</em>}</li>
 *   <li>{@link org.icyphy.linguaFranca.impl.ReactionImpl#getCode <em>Code</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ReactionImpl extends MinimalEObjectImpl.Container implements Reaction
{
  /**
   * The cached value of the '{@link #getTriggers() <em>Triggers</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTriggers()
   * @generated
   * @ordered
   */
  protected EList<String> triggers;

  /**
   * The cached value of the '{@link #getGets() <em>Gets</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGets()
   * @generated
   * @ordered
   */
  protected Gets gets;

  /**
   * The cached value of the '{@link #getSets() <em>Sets</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSets()
   * @generated
   * @ordered
   */
  protected Sets sets;

  /**
   * The default value of the '{@link #getCode() <em>Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCode()
   * @generated
   * @ordered
   */
  protected static final String CODE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCode() <em>Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCode()
   * @generated
   * @ordered
   */
  protected String code = CODE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ReactionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LinguaFrancaPackage.Literals.REACTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getTriggers()
  {
    if (triggers == null)
    {
      triggers = new EDataTypeEList<String>(String.class, this, LinguaFrancaPackage.REACTION__TRIGGERS);
    }
    return triggers;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Gets getGets()
  {
    return gets;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetGets(Gets newGets, NotificationChain msgs)
  {
    Gets oldGets = gets;
    gets = newGets;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LinguaFrancaPackage.REACTION__GETS, oldGets, newGets);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setGets(Gets newGets)
  {
    if (newGets != gets)
    {
      NotificationChain msgs = null;
      if (gets != null)
        msgs = ((InternalEObject)gets).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LinguaFrancaPackage.REACTION__GETS, null, msgs);
      if (newGets != null)
        msgs = ((InternalEObject)newGets).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LinguaFrancaPackage.REACTION__GETS, null, msgs);
      msgs = basicSetGets(newGets, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LinguaFrancaPackage.REACTION__GETS, newGets, newGets));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Sets getSets()
  {
    return sets;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSets(Sets newSets, NotificationChain msgs)
  {
    Sets oldSets = sets;
    sets = newSets;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, LinguaFrancaPackage.REACTION__SETS, oldSets, newSets);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSets(Sets newSets)
  {
    if (newSets != sets)
    {
      NotificationChain msgs = null;
      if (sets != null)
        msgs = ((InternalEObject)sets).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - LinguaFrancaPackage.REACTION__SETS, null, msgs);
      if (newSets != null)
        msgs = ((InternalEObject)newSets).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - LinguaFrancaPackage.REACTION__SETS, null, msgs);
      msgs = basicSetSets(newSets, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LinguaFrancaPackage.REACTION__SETS, newSets, newSets));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCode()
  {
    return code;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCode(String newCode)
  {
    String oldCode = code;
    code = newCode;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LinguaFrancaPackage.REACTION__CODE, oldCode, code));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LinguaFrancaPackage.REACTION__GETS:
        return basicSetGets(null, msgs);
      case LinguaFrancaPackage.REACTION__SETS:
        return basicSetSets(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LinguaFrancaPackage.REACTION__TRIGGERS:
        return getTriggers();
      case LinguaFrancaPackage.REACTION__GETS:
        return getGets();
      case LinguaFrancaPackage.REACTION__SETS:
        return getSets();
      case LinguaFrancaPackage.REACTION__CODE:
        return getCode();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LinguaFrancaPackage.REACTION__TRIGGERS:
        getTriggers().clear();
        getTriggers().addAll((Collection<? extends String>)newValue);
        return;
      case LinguaFrancaPackage.REACTION__GETS:
        setGets((Gets)newValue);
        return;
      case LinguaFrancaPackage.REACTION__SETS:
        setSets((Sets)newValue);
        return;
      case LinguaFrancaPackage.REACTION__CODE:
        setCode((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LinguaFrancaPackage.REACTION__TRIGGERS:
        getTriggers().clear();
        return;
      case LinguaFrancaPackage.REACTION__GETS:
        setGets((Gets)null);
        return;
      case LinguaFrancaPackage.REACTION__SETS:
        setSets((Sets)null);
        return;
      case LinguaFrancaPackage.REACTION__CODE:
        setCode(CODE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LinguaFrancaPackage.REACTION__TRIGGERS:
        return triggers != null && !triggers.isEmpty();
      case LinguaFrancaPackage.REACTION__GETS:
        return gets != null;
      case LinguaFrancaPackage.REACTION__SETS:
        return sets != null;
      case LinguaFrancaPackage.REACTION__CODE:
        return CODE_EDEFAULT == null ? code != null : !CODE_EDEFAULT.equals(code);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (triggers: ");
    result.append(triggers);
    result.append(", code: ");
    result.append(code);
    result.append(')');
    return result.toString();
  }

} //ReactionImpl
