// Doxygen group definitions
package docs;

/**
 * @defgroup CLI CLI
 *
 * Classes that implement the command line interface.
 */

/**
 * @defgroup Diagram Diagram
 *
 * Classes that implement the diagram server.
 */

/**
 * @defgroup Docker Docker
 *
 * Classes that implement the docker file generation.
 */

/**
 * @defgroup Federated Federated
 *
 * Classes that implement the federated code generator.
 */

/**
 * @defgroup Generated Generated
 *
 * Classes that are generated by Xtext.
 */

/**
 * @defgroup Generator Generator
 *
 * Classes that realize the code generator.
 */

/**
 * @defgroup Infrastructure Infrastructure
 *
 * Classes that provide infrastructure for the code generator including the Xtext framework.
 */

/**
 * @defgroup Instances Instances
 *
 * These classes represent instances of reactors and their parts. They differ from the
 * AST (abstract syntax tree) classes generated by Xtext.
 */

/**
 * @defgroup LSP LSP
 *
 * Classes that implement the Language Server Protocol.
 */

/**
 * @defgroup Tests Tests
 *
 * Classes that implement the tests.
 */

/**
 * @defgroup Utilities Utilities
 *
 * Utility classes used in the code generator.
 */

/**
 * @defgroup Validation Validation
 *
 * Classes that validate Lingua Franca programs and provide feedback to the user.
 */
