/*
 * generated by Xtext 2.18.0
 */
package org.icyphy.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class LinguaFrancaWebModule extends AbstractLinguaFrancaWebModule {
}
