name: Report code coverage to CodeCov
inputs:
  files:
    description: 'list of coverage files to send to CodeCov'
    required: true
runs:
  using: "composite"
  steps:
    - name: Report code coverage to CodeCov
      uses: Wandalen/wretry.action@v1.3.0
      with:
        attempt_limit: 5
        attempt_delay: 20000
        action: codecov/codecov-action@v3.1.4
        with: |
          files: ${{ inputs.files }}
          fail_ci_if_error: true
          verbose: true
          token: 18fd5ab8-d6ba-4f5d-b0f4-7c26340ab98c
