name: TEST_FLOW 

on:
  #push:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  led-test:
    if: contains(github.event.pull_request.labels.*.name, 'act-lf-led')
    uses: lf-lang/act-lf-testbed/.github/workflows/act-lfdev-led.yml@main
    secrets: inherit
