# Tests for embedded platforms
name: CI (embedded platforms)

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, converted_to_draft]
  merge_group:

env:
  # 2020.11
  vcpkgGitRef: 0bf3923f9fab4001c00f0f429682a0853b5749e0

concurrency:
  group: all-embedded-${{ github.ref }}-${{ github.event_path }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  check-diff:
    uses: ./.github/workflows/check-diff.yml

  c-embedded:
    uses: ./.github/workflows/c-embedded.yml
    needs: check-diff
    if: ${{ needs.check-diff.outputs.run_c == 'true' }}

  # Add more languages if supported
