name: Build trace tools

on:
  workflow_call:
    inputs:
      all-platforms:
        required: false
        default: true
        type: boolean

jobs:
  build-trace-tools:
    strategy:
      matrix:
        platform: ${{ (inputs.all-platforms && fromJSON('["ubuntu-latest", "macos-latest", "windows-latest"]')) || fromJSON('["ubuntu-latest"]') }}
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out lingua-franca repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Run make
        working-directory: ./util/tracing
        run: make
        shell: bash
