name: Check labels

on:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check that a label has been assigned
        uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: "feature, enhancement, fix, bug, bugfix, cleanup, refactoring, documentation, docs, test, tests, testing, upgrade, bump, dependency, version, misc, miscellaneous, ignore, exclude, trivial, duplicate, question, invalid, wontfix, ci, automated, experimental"
