name: Non-target-specific

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      all:
        type: boolean

env:
  # 2020.11
  vcpkgGitRef: 0bf3923f9fab4001c00f0f429682a0853b5749e0

concurrency:
  group: only-non-target-specific-${{ github.ref }}-${{ github.event_path }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:

  # Run the serialization tests
  serialization:
    if: ${{ inputs.all || github.event.pull_request.draft }}
    uses: ./.github/workflows/serialization-tests.yml
