name: Python

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      all:
        default: true
        type: boolean

env:
  # 2020.11
  vcpkgGitRef: 0bf3923f9fab4001c00f0f429682a0853b5749e0

concurrency:
  group: only-py-${{ github.ref }}-${{ github.event_path }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  # Run the Python integration tests.
  py-tests:
    uses: ./.github/workflows/py-tests.yml
    if: ${{ inputs.all || github.event.pull_request.draft }}
    with:
      all-platforms: ${{ !github.event.pull_request.draft  }}
