name: TypeScript

on:
  workflow_dispatch:
  workflow_call:

env:
  # 2020.11
  vcpkgGitRef: 0bf3923f9fab4001c00f0f429682a0853b5749e0

concurrency:
  group: only-ts-${{ github.ref }}-${{ github.event_path }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  # Run the TypeScript benchmark tests.
  benchmarking:
    uses: lf-lang/benchmarks-lingua-franca/.github/workflows/benchmark-tests.yml@gradle
    with:
      target: "TS"

  # Run the TypeScript integration tests.
  ts-tests:
    uses: ./.github/workflows/ts-tests.yml
    with:
      all-platforms: ${{ !github.event.pull_request.draft  }}
