name: Publish org.lflang to GitHub Packages
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Prepare build environment
        if: !contains(github.event.release.tag_name, 'nightly')
        uses: ./.github/actions/prepare-build-env
      - name: Publish package
        if: !contains(github.event.release.tag_name, 'nightly')
        uses: gradle/gradle-build-action@v2.1.7
        with:
          arguments: org.lflang:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}