package org.lflang.generator.cpp

import org.lflang.AttributeUtils
import org.lflang.ast.ASTUtils
import org.lflang.generator.PrependOperator
import org.lflang.joinLn
import org.lflang.joinWithLn
import org.lflang.lf.Input
import org.lflang.lf.Reactor
import org.lflang.reactor
import org.lflang.target.property.BuildTypeProperty
import org.lflang.target.property.CmakeIncludeProperty
import org.lflang.target.property.Ros2DependenciesProperty
import org.lflang.target.property.RuntimeVersionProperty
import org.lflang.toUnixString
import java.nio.file.Path

/** A C++ code generator for creating the required files for defining a ROS2 package. */
class CppRos2PackageGenerator(generator: CppGenerator) {
    private val fileConfig = generator.fileConfig
    private val targetConfig = generator.targetConfig
    val reactorCppSuffix: String = if (targetConfig.isSet(RuntimeVersionProperty.INSTANCE)) targetConfig.get(RuntimeVersionProperty.INSTANCE) else "default"
    val reactorCppName = "reactor-cpp-$reactorCppSuffix"
    private val dependencies =
        listOf("rclcpp", "rclcpp_components", reactorCppName) + (
                if (targetConfig.isSet(Ros2DependenciesProperty.INSTANCE)) targetConfig.get(Ros2DependenciesProperty.INSTANCE) else listOf<String>())

    @Suppress("PrivatePropertyName") // allows us to use capital S as variable name below
    private val S = '$' // a little trick to escape the dollar sign with $S

    var nodeGenerators = emptyList<CppRos2NodeGenerator>()

    fun generatePackageXml(): String {
        return """
            |<?xml version="1.0"?>
            |<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
            |<package format="3">
            |  <name>${fileConfig.name}</name>
            |  <version>0.0.0</version>
            |  <description>Autogenerated from ${fileConfig.srcFile}</description>
            |  <maintainer email="todo@todo.com">Todo</maintainer>
            |  <license>Todo</license>
            |  
            |  <buildtool_depend>ament_cmake</buildtool_depend>
            |  <buildtool_depend>ament_cmake_auto</buildtool_depend>
            |  
        ${" |"..dependencies.joinWithLn { "<depend>$it</depend>" }}
            |  <depend>lf_msgs_ros</depend>
            |  <depend>lf_wrapped_msgs</depend>
            |  <test_depend>ament_lint_auto</test_depend>
            |  <test_depend>ament_lint_common</test_depend>
            |
            |  <exec_depend>ament_index_python</exec_depend>
            |
            |  <export>
            |    <build_type>ament_cmake</build_type>
            |  </export>
            |</package>
        """.trimMargin()
    }

    fun generatePackageCmake(sources: List<Path>): String {
        // Resolve path to the cmake include files if any was provided
        val includeFiles = targetConfig.get(CmakeIncludeProperty.INSTANCE)?.map { fileConfig.srcPath.resolve(it).toUnixString() }

        return with(PrependOperator) {
            with(CppGenerator) {
                """
                |cmake_minimum_required(VERSION $MINIMUM_CMAKE_VERSION)
                |project(${fileConfig.name} VERSION 0.0.0 LANGUAGES CXX)
                |
                |# require C++ $CPP_VERSION
                |set(CMAKE_CXX_STANDARD $CPP_VERSION CACHE STRING "The C++ standard is cached for visibility in external tools." FORCE)
                |set(CMAKE_CXX_STANDARD_REQUIRED ON)
                |set(CMAKE_CXX_EXTENSIONS OFF)
                |
                |set(DEFAULT_BUILD_TYPE "${targetConfig.get(BuildTypeProperty.INSTANCE)}")
                |if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
                |set    (CMAKE_BUILD_TYPE "$S{DEFAULT_BUILD_TYPE}" CACHE STRING "Choose the type of build." FORCE)
                |endif()
                |
                |# Invoke find_package() for all build and buildtool dependencies.
                |find_package(ament_cmake_auto REQUIRED)
                |find_package(lf_msgs_ros REQUIRED)
                |find_package(lf_wrapped_msgs REQUIRED)
                |ament_auto_find_build_dependencies()
                |include_directories(
                |   include 
                |   src/${fileConfig.srcGenBasePath.relativize(fileConfig.srcGenPkgPath).toUnixString()}
                |   "$S{LF_SRC_PKG_PATH}/src"
                |   "$S{PROJECT_SOURCE_DIR}/include/"
                |   "$S{PROJECT_SOURCE_DIR}/src/"
                |   "$S{PROJECT_SOURCE_DIR}/src/__include__"
                | )
                ${ nodeGenerators.map {
                    """
                    |add_executable(${it.nodeName}
                    |  src/${it.nodeName}.cc
                ${" |  src/"..sources.joinWithLn { it.toUnixString() }}
                    |)
                    |ament_target_dependencies(${it.nodeName} ${dependencies.joinToString(" ")} lf_msgs_ros lf_wrapped_msgs)
                    |target_link_libraries(${it.nodeName} $reactorCppName)
                    |
                    |install(
                    |     TARGETS ${it.nodeName}
                    |     DESTINATION lib/$S{PROJECT_NAME}
                    |   )  
                    |install(DIRECTORY launch
                    |   DESTINATION share/$S{PROJECT_NAME})
                    |
                    |if(MSVC)
                    |  target_compile_options(${it.nodeName} PRIVATE /W4)
                    |else()
                    |  target_compile_options(${it.nodeName} PRIVATE -Wall -Wextra -pedantic)
                    |endif()
                    """
                }.joinLn()}
                |
                |
                |
                |ament_package()
                |
            ${" |"..(includeFiles?.joinWithLn { "include(\"$it\")" } ?: "")}
            """.trimMargin()
            }
        }
    }
    // Generates a Python code string that represents the structure of a given Reactor object, detailing its instantiations and connections
    private fun createReactorStructurePython(reactor : Reactor, nodeName : String = "") : String {
        var s = "Reactor(\"$nodeName\""
        s += "," + System.lineSeparator()
        s+= "["
        var isFirst : Boolean = true
        for (inst in reactor.instantiations) {
            if (isFirst) isFirst = false
            else s+=", "
            s+="Instantiation(\"${inst.name}\", "
            if (AttributeUtils.isFederate(inst)) {
                val instGen = nodeGenerators.filter{ it.reactor == inst.reactor}.first()
                s+="\"${instGen.nodeName}\", ${createReactorStructurePython(inst.reactor, instGen.nodeName)}"
            } else {
                s+="None, ${createReactorStructurePython(inst.reactor)}"
            }
            s+= ")"
        }
        s+= "]," + System.lineSeparator()
        s+= "["
        isFirst = true
        for (con in reactor.connections) {
            if (isFirst) isFirst = false
            else s+=", "
            s+="Connection("
            s+= "["
            isFirst = true
            for (leftP in con.leftPorts) {
                if (isFirst) isFirst = false
                else s+=", "

                s+= "Port(${if (leftP.container != null) "\"${leftP.container.name}\"" else "None" }" +
                        ", \"${leftP.variable.name}\", ${if (leftP.variable is Input) "True" else "False"})"
            }
            s+= "], "
            s+= "["
            isFirst = true
            for (rightP in con.rightPorts) {
                if (isFirst) isFirst = false
                else s+=", "
                s+= "Port(${if (rightP.container != null) "\"${rightP.container.name}\"" else "None" }, " +
                        "\"${rightP.variable.name}\", ${if (rightP.variable is Input) "True" else "False"})"
            }
            s+= "], "
            s+= if (con.isPhysical) "True" else "False"
            s+= ", "
            s+= if (con.delay != null) ASTUtils.getLiteralTimeValue(con.delay).toNanoSeconds() else "None"
            s+=")"
        }
        s+= "]"
        s+= ")" + System.lineSeparator()
        return s
    }

    fun generateLaunchFile(): String {
        val mainReactorNodeGen = nodeGenerators.filter{ it.reactor.isMain}.first()
        val reactorStructurePython = createReactorStructurePython(mainReactorNodeGen.reactor)
        return """
            |from __future__ import annotations
            |from typing import List, Tuple, Dict, Optional, Deque
            |from dataclasses import dataclass
            |from collections import deque
            |from launch import LaunchContext, LaunchDescription
            |from launch_ros.actions import Node
            |from launch.actions import OpaqueFunction, DeclareLaunchArgument
            |from launch.substitutions import LocalSubstitution, LaunchConfiguration
            |from pprint import pprint as prettyprint
            |
            |# if a node fails (exit code != 0) the launch file is exited with the same exit code
            |# this got implemented to allow LF tests with ROS2 launch files
            |def relay_node_fail_to_launch(context: LaunchContext):
            |    assert(isinstance(context, LaunchContext))
            |    # event is instance of launch.events.process.ProcessExited
            |    return_code = LocalSubstitution("event.returncode").perform(context)
            |    assert(isinstance(return_code, int))
            |    if return_code != 0:
            |        exit(return_code)
            |
            |class Port:
            |   instance_name: str
            |   name: str
            |   is_input: bool
            |   
            |   def __init__(self, _inst_name, _port_name, _is_input):
            |       self.instance_name = _inst_name
            |       self.name = _port_name
            |       self.is_input = _is_input
            |
            |class Connection:
            |   leftPorts: List[Port]
            |   rightPorts: List[Port]
            |   physical: bool
            |   delay: Optional[int]
            |   
            |   def __init__(self, lPorts, rPorts, isPhysical, _delay):
            |       self.leftPorts = lPorts
            |       self.rightPorts = rPorts
            |       self.physical = isPhysical
            |       self.delay = _delay
            |       
            |class Instantiation:
            |   name: str
            |   executable: str
            |   reactor: Reactor
            |   
            |   def __init__(self, _name, _executable, _reactor):
            |       self.name = _name
            |       self.executable = _executable
            |       self.reactor = _reactor
            |
            |class Reactor:
            |   classname: str
            |   instantiations: List[Instantiation]
            |   connections: List[Connection]
            |   
            |   def __init__(self, _classname, _instantiations, _connections):
            |       self.classname = _classname
            |       self.instantiations = _instantiations
            |       self.connections = _connections
            |       
            |mainInstance : Reactor = Instantiation("${mainReactorNodeGen.reactor.name}", "${mainReactorNodeGen.nodeName}",
            |$reactorStructurePython
            |)
            |
            |NODE_SELECTION_LIST_ARG_NAME = "node_selection_list"
            |ALL_NODES_INDICATOR = "__all__" # Special value to indicate all nodes should be launched
            |RELAY_FAIL_ARG_NAME = "relay_node_fail_to_launch"
            |
            |                   
            |def generate_launch_description():
            |   # Declare launch argument for node list
            |   node_selection_list_arg = DeclareLaunchArgument(
            |       NODE_SELECTION_LIST_ARG_NAME, default_value=ALL_NODES_INDICATOR,
            |       description='Comma-separated list of nodes to launch based on their lf federate prefix (if not specified, all nodes will be launched)'
            |       )
            |       
            |   # Declare launch argument for exit on node fail
            |   relay_fail_arg = DeclareLaunchArgument(
            |       RELAY_FAIL_ARG_NAME, default_value="True",
            |       description='If true, when a node exits with an exit code other than 0 the launch will exit with the same code.'
            |       )
            |
            |   # this dict accumulates parameters for each node based on the connections (of the containing node)
            |   prefix_param_dict : Dict[str, Dict[str,str]] = {}
            |   # str is container prefix, list is connections from container regarding this instance
            |   # instances are processed in a breath-first manner 
            |   # (to make sure that the respective parent has already been processed for each instance)
            |   instances_todo : Deque[Tuple[str, Instantiation, List[Connection]]] = deque([("", mainInstance, [])]) 
            |   
            |   while instances_todo:
            |       prefix, instance, connections = instances_todo.popleft()
            |       lf_federate_prefix = prefix + "/" + instance.name
            |       
            |       # add child instances to queue for later processing
            |       for next_inst in instance.reactor.instantiations:
            |           # filter connections that concern the child instance
            |           next_conns = [con for con in instance.reactor.connections if
            |               any(p.instance_name == next_inst.name for p in con.leftPorts + con.rightPorts)]   
            |           instances_todo.append((lf_federate_prefix, next_inst, next_conns))
            |       
            |       # create node parameters
            |       generate_instance_parameters(lf_federate_prefix, prefix, instance, connections, prefix_param_dict)
            |                   
            |   return LaunchDescription([node_selection_list_arg, relay_fail_arg,
            |       OpaqueFunction(function=create_node_launch_descriptions, args=[prefix_param_dict])])
            |   
            |def create_node_launch_descriptions(context, prefix_param_dict) -> List[Node]:
            |   # launch nodes if they are federate (have an executable) with parameters from prefix_param_dict
            |   to_search_feds : Deque[Tuple[str,Instantiation]] = deque([("", mainInstance)])
            |   node_selection_list = LaunchConfiguration(NODE_SELECTION_LIST_ARG_NAME).perform(context)
            |   relay_node_fail = LaunchConfiguration(RELAY_FAIL_ARG_NAME).perform(context)
            |   # dict is use to pass parameter conditionally
            |   relay_node_fail_dict = dict(on_exit=OpaqueFunction(function=relay_node_fail_to_launch))
            |   if relay_node_fail.lower() in ['0', 'false']:
            |       relay_node_fail_dict = {}
            |   launch_all_nodes = False
            |   if node_selection_list == ALL_NODES_INDICATOR:
            |       launch_all_nodes = True
            |   else:
            |       node_selection_list = node_selection_list.split(",")
            |   nodes = []
            |   while to_search_feds:
            |       [prefix, instance] = to_search_feds.popleft()
            |       fed_prefix = prefix + "/" + instance.name
            |       for inst in instance.reactor.instantiations:
            |           to_search_feds.append((fed_prefix, inst))
            |       if instance.executable != None:
            |           if launch_all_nodes or fed_prefix in node_selection_list:
            |               nodes.append(Node(package='${fileConfig.name}',
            |                                  executable=instance.executable,
            |                                  name=fed_prefix.replace("/","_"),
            |                                  parameters=[prefix_param_dict[fed_prefix]],
            |                                  **relay_node_fail_dict
            |                                  )
            |                               )
            |               print("launching node with prefix " + fed_prefix)
            |               prettyprint(prefix_param_dict[fed_prefix])
            |   return nodes
            |   
            |def generate_instance_parameters(lf_federate_prefix: str, prefix: str, instance: Instantiation, connections: List[Connection], prefix_param_dict):
            |    param_dict = {"lf_federate_prefix": lf_federate_prefix}
            |    for con in connections:
            |       update_param_dict_for_con(con, instance, lf_federate_prefix, prefix, param_dict, prefix_param_dict)
            |    prefix_param_dict[lf_federate_prefix] = param_dict
            |    
            |    
            |def update_param_dict_for_con(con, instance, lf_federate_prefix, prefix, instance_param_dict, prefix_param_dict):
            |   # con is from parent concerning the instance
            |   physical_string = "_physical" if con.physical else ""
            |   for leftP, rightP in zip(con.leftPorts, con.rightPorts):
            |      if leftP.instance_name == instance.name and not leftP.is_input:
            |         instance_param_dict[leftP.name + physical_string] = lf_federate_prefix + "/" + leftP.name
            |      if rightP.instance_name == instance.name and leftP.is_input and leftP.instance_name == None:
            |         if leftP.name in prefix_param_dict[prefix]:
            |            instance_param_dict[rightP.name] = prefix_param_dict[prefix][leftP.name]
            |         if leftP.name + "_physical" in prefix_param_dict[prefix]:
            |            instance_param_dict[rightP.name+"_physical"] = prefix_param_dict[prefix][leftP.name+"_physical"]
            |      if rightP.instance_name == instance.name and rightP.is_input and leftP.instance_name != None:
            |         instance_param_dict[rightP.name + physical_string] = prefix +"/"+ leftP.instance_name + "/" + leftP.name
            |         if con.delay is not None:
            |            instance_param_dict[rightP.name + physical_string + "_delay"] = con.delay
            |      if leftP.instance_name == instance.name and rightP.instance_name == None and not rightP.is_input:
            |         # connection like r{x.port -> out} while current instance is x
            |         # we go through the reactors to see if parent.out is used to replace it with x.port
            |         name_to_search_for = prefix + "/" + rightP.name
            |         print(name_to_search_for)
            |         for key in prefix_param_dict:
            |            for key2 in prefix_param_dict[key]:
            |                if prefix_param_dict[key][key2] == name_to_search_for:
            |                   prefix_param_dict[key][key2] = lf_federate_prefix + "/" + leftP.name
            |   
        """.trimMargin()

    }

    fun generateBinScript(): String {
        val relPath = fileConfig.binPath.relativize(fileConfig.outPath).toUnixString()

        return """
            |#!/bin/bash
            |script_dir="$S(dirname -- "$S(readlink -f -- "${S}0")")"
            |source "$S{script_dir}/$relPath/src-gen/install/setup.sh"
            |ros2 launch ${fileConfig.name} default.launch.py
        """.trimMargin()
    }
}
