/*
 * generated by Xtext 2.23.0
 */
package org.lflang;

import org.lflang.scoping.LFGlobalScopeProvider;
import org.lflang.validation.LFNamesAreUniqueValidationHelper;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LFRuntimeModule extends AbstractLFRuntimeModule {
    /** Establish a binding to our custom global scope provider. */
    @Override
    public Class<LFGlobalScopeProvider> bindIGlobalScopeProvider() {
        return LFGlobalScopeProvider.class;
    }

    /** Establish a binding to a helper that checks that names are unique. */
    public Class<LFNamesAreUniqueValidationHelper> bindNamesAreUniqueValidationHelper() {
        return LFNamesAreUniqueValidationHelper.class;
    }
    /** Establish a binding to our custom resource description strategy. */
//    fun bindIDefaultResourceDescriptionStrategy(): Class<out IDefaultResourceDescriptionStrategy> = LFResourceDescriptionStrategy::class.java
    

}
