/*
 * generated by Xtext 2.25.0
 */
package org.lflang

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
open class LFStandaloneSetup : LFStandaloneSetupGenerated()
