/*
 * generated by Xtext 2.25.0
 */

package org.lflang;


import org.eclipse.xtext.util.Modules2;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;

/**
 * Initialization support for running Xtext languages without
 * Equinox extension registry.
 *
 * See {@link LFRuntimeModule}, the base Guice module for LF services.
 */
public class LFStandaloneSetup extends LFStandaloneSetupGenerated {

	private final Module[] modules;

	public LFStandaloneSetup() {
		this.modules = new Module[] {new LFRuntimeModule()};
	}

	public LFStandaloneSetup(Module... modules) {
		this.modules = modules.clone();
	}

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(this.modules));
	}
}
